{\rtf1\ansi\ansicpg1252\cocoartf2638
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 .AppleSystemUIFontMonospaced-Regular;}
{\colortbl;\red255\green255\blue255;\red224\green232\blue240;}
{\*\expandedcolortbl;;\cssrgb\c90196\c92941\c95294;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs23\fsmilli11900 \cf2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 plugins:\
  - jekyll-paginate\
  - jekyll-sitemap\
  - jekyll-gist\
  - jekyll-feed\
  - jemoji\
  - jekyll-include-cache\
}